-- Your SQL goes here
CREATE TABLE users (
  id VARCHAR NOT NULL PRIMARY KEY,
  uname VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  join_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  avatar VARCHAR NOT NULL DEFAULT '',
  email VARCHAR NOT NULL DEFAULT '',
  intro  VARCHAR NOT NULL DEFAULT '',
  location VARCHAR NOT NULL DEFAULT '',
  nickname VARCHAR NOT NULL DEFAULT '',
  permission SMALLINT NOT NULL DEFAULT 3,
  link VARCHAR NOT NULL DEFAULT '',
  auth_from VARCHAR NOT NULL DEFAULT '',
  email_confirmed BOOLEAN NOT NULL DEFAULT 'f',
  UNIQUE (uname)
);